//go:build ncnn

package classifier

import (
	"path/filepath"
	"time"

	"github.com/tphakala/birdnet-go/internal/errors"
	"github.com/tphakala/birdnet-go/internal/inference"
	"github.com/tphakala/birdnet-go/internal/logger"
)

// initializeNCNNModel loads and initialises the NCNN classifier backend.
//
// Model files are loaded from the directory specified by
// BirdNETConfig.NCNNModelDir. The preferred production pair is
// birdnet_cnn_only.param/bin, generated by splitting source_models/BirdNET_V2.4.onnx
// at the spectrogram handoff boundary and converting the CNN-only graph with
// onnx2ncnn.
//
// The backend performs Go-native mel spectrogram preprocessing on raw audio
// before passing the result to the NCNN CNN graph.
func (bn *BirdNET) initializeNCNNModel() error {
	start := time.Now()
	log := GetLogger()

	cfg := bn.Settings.BirdNET

	modelDir := cfg.NCNNModelDir
	if modelDir == "" {
		modelDir = "model"
	}

	modelStatus := InspectNCNNModelDir(modelDir)
	switch {
	case !modelStatus.Found:
		return errors.Newf("no recognized NCNN model files found in %s", modelDir).
			Category(errors.CategoryModelInit).
			Context("ncnn_model_dir", modelDir).
			Build()
	case !modelStatus.Validated:
		return errors.Newf(
			"NCNN model directory %s is missing validation marker %s",
			modelDir,
			filepath.Join(modelDir, NCNNValidationMarkerName),
		).
			Category(errors.CategoryModelInit).
			Context("ncnn_model_dir", modelDir).
			Context("ncnn_validation_marker", NCNNValidationMarkerName).
			Build()
	}

	opts := inference.NCNNClassifierOptions{
		ModelDir:  modelDir,
		Threads:   cfg.Threads,
		UseVulkan: cfg.NCNNUseVulkan,
	}

	classifier, err := inference.NewNCNNClassifier(opts)
	if err != nil {
		return errors.New(err).
			Category(errors.CategoryModelInit).
			Context("ncnn_model_dir", modelDir).
			Context("ncnn_use_vulkan", cfg.NCNNUseVulkan).
			ModelContext("", bn.ModelInfo.ID).
			Timing("ncnn-model-init", time.Since(start)).
			Build()
	}

	bn.classifier = classifier

	backend := "cpu"
	if cfg.NCNNUseVulkan {
		backend = "vulkan"
	}
	log.Info("NCNN model initialized",
		logger.String("model_dir", modelDir),
		logger.String("backend", backend),
		logger.Int("species", classifier.NumSpecies()),
		logger.Duration("init_time", time.Since(start)))

	return nil
}

// isNCNNSupported returns true when the binary is built with NCNN support.
func isNCNNSupported() bool { return true }
