//go:build ncnn

// Package ncnn provides NCNN-based inference for bird species classification.
//
// Build with: -tags ncnn
//
// On the Arduino Uno Q, set these environment variables before building:
//
//	CGO_CFLAGS=-I/home/arduino/ncnn/build/install/include
//	CGO_LDFLAGS=-L/home/arduino/ncnn/build/install/lib -lncnn -lglslang \
//	  -lMachineIndependent -lOSDependent -lGenericCodeGen -lSPIRV \
//	  -lglslang-default-resource-limits -lvulkan -lstdc++ -lgomp -lpthread -lm -ldl
package ncnn

/*
#cgo CFLAGS: -I/home/arduino/ncnn/build/install/include
#cgo LDFLAGS: -L/home/arduino/ncnn/build/install/lib -lncnn -lglslang -lMachineIndependent -lOSDependent -lGenericCodeGen -lSPIRV -lglslang-default-resource-limits -lvulkan -lstdc++ -lgomp -lpthread -lm -ldl
#include <stdlib.h>
#include "ncnn/c_api.h"
*/
import "C"
import (
	"fmt"
	"path/filepath"
	"unsafe"
)

const (
	// inputName is the blob name of the CNN sub-model's input layer.
	// This comes from the onnx2ncnn conversion of birdnet_cnn.onnx and is
	// the output of the concatenate layer that merges two mel spectrogram paths.
	inputName = "model/concatenate/concat"

	// outputName is the blob name of the CNN sub-model's output layer.
	outputName = "Identity"

	// Expected input dimensions: [C=2, H=511, W=96] in NCHW (NCNN planar format).
	inputW = 96
	inputH = 511
	inputC = 2

	// Number of species the model outputs.
	numSpeciesDefault = 6522
)

// Classifier implements inference using the NCNN backend with Go-native
// mel spectrogram preprocessing.
//
// Architecture:
//   - Raw audio (144 000 samples at 48 kHz) → ComputeMelSpectrograms()
//     → two planar spectrogram channels [C=2, H=511, W=96]
//   - Channels fed into the BirdNET CNN sub-model via the NCNN C API
//   - Output: 6522 raw logits (pre-sigmoid)
type Classifier struct {
	net        C.ncnn_net_t
	numSpecies int
	useVulkan  bool
}

// Options configures an NCNN classifier.
type Options struct {
	// ModelDir is the directory containing birdnet_cnn.param and birdnet_cnn.bin.
	// These are the CNN sub-model files generated by onnx2ncnn from birdnet_cnn.onnx.
	ModelDir string
	// Threads sets the number of CPU threads. 0 uses NCNN's default (all cores).
	Threads int
	// UseVulkan enables Vulkan GPU acceleration (requires Vulkan-capable GPU).
	// On the Arduino Uno Q with Adreno 702, Vulkan is available via Mesa Turnip.
	UseVulkan bool
}

// New creates a new NCNN Classifier. It loads the model from ModelDir and
// initialises Go-side mel spectrogram preprocessing tables.
func New(opts Options) (*Classifier, error) {
	net := C.ncnn_net_create()

	ncnnOpt := C.ncnn_option_create()
	if opts.Threads > 0 {
		C.ncnn_option_set_num_threads(ncnnOpt, C.int(opts.Threads))
	}
	if opts.UseVulkan {
		C.ncnn_option_set_use_vulkan_compute(ncnnOpt, 1)
	}
	C.ncnn_net_set_option(net, ncnnOpt)
	C.ncnn_option_destroy(ncnnOpt)

	paramPath := filepath.Join(opts.ModelDir, "birdnet_cnn.param")
	binPath := filepath.Join(opts.ModelDir, "birdnet_cnn.bin")

	cParam := C.CString(paramPath)
	defer C.free(unsafe.Pointer(cParam))
	if ret := C.ncnn_net_load_param(net, cParam); ret != 0 {
		C.ncnn_net_destroy(net)
		return nil, fmt.Errorf("failed to load ncnn param from %s: %d", paramPath, ret)
	}

	cBin := C.CString(binPath)
	defer C.free(unsafe.Pointer(cBin))
	if ret := C.ncnn_net_load_model(net, cBin); ret != 0 {
		C.ncnn_net_destroy(net)
		return nil, fmt.Errorf("failed to load ncnn model from %s: %d", binPath, ret)
	}

	return &Classifier{
		net:        net,
		numSpecies: numSpeciesDefault,
		useVulkan:  opts.UseVulkan,
	}, nil
}

// Predict runs mel spectrogram preprocessing then NCNN inference on raw audio samples.
//
// samples must contain exactly 144 000 float32 values (48 kHz × 3 s).
// Returns raw logits (pre-sigmoid) for each of the 6522 BirdNET species.
func (c *Classifier) Predict(samples []float32) ([]float32, error) {
	// Compute two-channel mel spectrogram: [2 × 511 × 96] in planar format.
	melData := ComputeMelSpectrograms(samples)
	if len(melData) != inputC*inputH*inputW {
		return nil, fmt.Errorf("mel spectrogram has unexpected size: got %d, want %d",
			len(melData), inputC*inputH*inputW)
	}

	// Create NCNN input mat: create_3d(W, H, C) with planar channel data.
	// Channel 0 (SPEC1) occupies the first H×W = 49056 floats,
	// Channel 1 (SPEC2) occupies the next H×W = 49056 floats.
	inMat := C.ncnn_mat_create_3d(C.int(inputW), C.int(inputH), C.int(inputC), nil)
	inData := (*float32)(C.ncnn_mat_get_data(inMat))
	melSlice := unsafe.Slice(inData, len(melData))
	copy(melSlice, melData)

	ex := C.ncnn_extractor_create(c.net)
	defer C.ncnn_extractor_destroy(ex)

	cInputName := C.CString(inputName)
	defer C.free(unsafe.Pointer(cInputName))
	C.ncnn_extractor_input(ex, cInputName, inMat)
	C.ncnn_mat_destroy(inMat)

	var outMat C.ncnn_mat_t
	cOutputName := C.CString(outputName)
	defer C.free(unsafe.Pointer(cOutputName))
	if ret := C.ncnn_extractor_extract(ex, cOutputName, &outMat); ret != 0 {
		return nil, fmt.Errorf("ncnn extraction failed: %d", ret)
	}
	defer C.ncnn_mat_destroy(outMat)

	outW := int(C.ncnn_mat_get_w(outMat))
	outData := (*float32)(C.ncnn_mat_get_data(outMat))
	predictions := make([]float32, outW)
	copy(predictions, unsafe.Slice(outData, outW))

	return predictions, nil
}

// NumSpecies returns the number of species classes the model outputs.
func (c *Classifier) NumSpecies() int {
	return c.numSpecies
}

// Close releases all NCNN resources.
func (c *Classifier) Close() {
	if c.net != nil {
		C.ncnn_net_destroy(c.net)
		c.net = nil
	}
}

// Name returns a human-readable backend identifier.
func (c *Classifier) Name() string {
	if c.useVulkan {
		return "ncnn-vulkan"
	}
	return "ncnn-cpu"
}
